# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Email Trigger

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

      - name: send email
        if: always()
        uses: https://github.com/subbu852386/actions/checkout@v2
        with:
            to: ${{ secrets.MAIL_TO }}
            from: Relevate <smtp.office365.com>
            subject: ${{ ele.repository }} ${{ele.workflow}} ${{ job.status }}
            priority: high
             convert_markdown: true
             html_body: |
               ### Job ${{ job.status }}

               ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)
