# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Send mail
        if: always()
        uses: https://github.com/subbu852386/actions/checkout@v2
        with:
            to: ${{ secrets.MAIL_TO }}
            from: Relevate <smtp.office365.com>
            subject: ${{ ele.repository }} ${{ele.workflow}} ${{ job.status }}
            priority: high
             convert_markdown: true
             html_body: |
               ### Job ${{ job.status }}

               ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)
