name: Node.js CI/CD

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

 

    - name: Install nodemailer
      run: npm install nodemailer

 

    - name: Send email notification
      run: |
        const nodemailer = require('nodemailer')

 

          const transporter = nodemailer.createTransport({
            service: 'YOUR_EMAIL_SERVICE', // e.g., 'Gmail' or 'Outlook'
            auth: {
              user: ${{ secrets.EMAIL_USERNAME }},
              pass: ${{ secrets.EMAIL_PASSWORD }}
            },
          });

 

          const message = {
            from: 'your-email@gmail.com',
            to: 'recipient@example.com',
            subject: 'GitHub Actions Workflow Completed',
            text: 'Your GitHub Actions workflow has completed successfully.',
          };

 

          transporter.sendMail(message, (error, info) => {
            if (error) {
              console.error('Error sending email:', error);
            } else {
              console.log('Email sent:', info.response);
            }
          });
